In [1]:
#Create a 3x3 matrix with values ranging from 0 to 8
import numpy as np

# Create a 3x3 matrix with values ranging from 0 to 8
matrix = np.arange(9).reshape(3, 3)

print(matrix)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [2]:
#Find the sum of all the elements in a NumPy array
import numpy as np
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
sum_of_elements = arr.sum()

print("Sum of all elements:", sum_of_elements)


Sum of all elements: 45


In [4]:

arr[arr % 2 != 0] = -1

print("Array after replacing odd no with -1:", arr)


Array after replacing odd no with -1: [[-1  2 -1]
 [ 4 -1  6]
 [-1  8 -1]]


In [5]:
#How to get the common items between two python NumPy arrays?
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([3, 4, 5, 6, 7])
common_items = np.intersect1d(arr1, arr2)

print("Common items between arr1 and arr2:", common_items)


Common items between arr1 and arr2: [3 4 5]


In [6]:
#How to get the positions where elements of two arrays match?
import numpy

a = numpy.array([0, 1, 2, 3, 4, 5, 6])
b = numpy.array([6, 5, 4, 3, 2, 1, 6])
numpy.where(a==b)

(array([3, 6], dtype=int64),)

In [7]:
#How to create a 2D array containing random floats between 5 and 10?
import numpy as np


rows = 3
cols = 4

random_array = 5 + np.random.random((rows, cols)) * 5

print("2D array of random floats between 5 and 10:")
print(random_array)


2D array of random floats between 5 and 10:
[[8.48571901 9.17806114 6.31515035 6.42516476]
 [9.03598781 8.15782251 6.35538318 5.77184002]
 [5.50327479 6.43199871 5.72659165 8.28787598]]


In [10]:
import numpy as np

# Create a sample 2D array
array = np.array([[3, 2, 5],
                  [1, 4, 6],
                  [7, 0, 8]])

# Define the index of the column to sort by
n = 1
# Sort the array by the nth column
sorted_array = array[array[:, n].argsort()]
print(sorted_array)


[[7 0 8]
 [3 2 5]
 [1 4 6]]


In [11]:
#How to tell if a given 2D array has null columns
import numpy as np
array = np.array([[1, 2, 0],
                  [0, 0, 0],
                  [3, 0, 4]])

# Check if any column is null
null_columns = np.all(array == 0, axis=0)

if np.any(null_columns):
    print("The array has null columns.")
    print("Indices of null columns:", np.where(null_columns)[0])
else:
    print("The array does not have null columns.")


The array does not have null columns.
